version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: movieswatcher
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: movies-watcher
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
